mapillary/OpenSfM

- viewer/reconstruction.html
Adding options to be able to show and hide the image planes in both walk and orbit mode.
The imagePlaneOpacity property of options is only set to 1 in walk mode since it does not add any value when showing the image planes in orbit mode.
Setting moving mode to walk explicitly before calling the setImagePlaneCamera function in correct circumstances instead of inside function because the method is now also called in orbit mode when a new camera is selected. Creating method for navigating to shot for the same reason.
.
> Adding options for showing and hiding the image planes

- README.md
I recieved the following error when building the csfm library in Ubuntu:
usr/local/lib/libceres.a(loss_function.cc.o): relocation R_X86_64_32S against `_ZTVN5ceres12ComposedLossE' can not be used when making a shared object; recompile with -fPIC
/usr/local/lib/libceres.a: error adding symbols: Bad value
SuiteSparse needed to be installed according to the shared library instructions in the [Ceres docs](http://ceres-solver.org/building.html) and Ceres needed to be compiled with the -fPIC option. I updated the readme accordingly.
The Ceres Ubuntu installation procedure has been simplified so I removed some outdated information.
I also added correct indentation for code blocks in list items.
> Updating ceres install instructions.

- bin/clean
- bin/plot_inliers
To visualize the results for some of the algorithms that includes or excludes feature matches along the pipeline I have created some functions that plot inliers and outliers. 
Two images from a data set needs to specified when running the file but since functions have been extracted a loop can easily be created to plot a number of image combinations.
Because the algorithms are actually run using loaded features and tracks the figures are not created instantly.
The results for two images in the Berlin data set can be seen below:
> Plot inliers

- .gitignore
- opensfm/src/CMakeLists.txt
Both homebrewed python 2.7 and system bundled Python.framework work fine. :)
(#13 is resolved)
> Works with Homebrewed Python in OS X

- opensfm/features.py
When image arrays are loaded in the dataset the default OpenCV color format **BGR** is reversed to **RGB.** When images are converted to grayscale for feature extraction the conversion code COLOR_**BGR**2GRAY is used.
The OpenCV docs state that "In case of a transformation to-from RGB color space, the order of the channels should be specified explicitly (RGB or BGR)". Since the grayscale conversion uses different weights for the color channels the correct conversion code should be COLOR_**RGB**2GRAY.
This affects the feature extraction and in the end the final reconstruction.
References:
* [cvtColor](http://docs.opencv.org/modules/imgproc/doc/miscellaneous_transformations.html#cvtcolor)
* [imread](http://docs.opencv.org/modules/highgui/doc/reading_and_writing_images_and_video.html#imread)
> Grayscale conversion

- bin/plot_inliers
I have added some figures to the plot inliers script. What you get now if specifying the options to plot everything is the following (Berlin dataset with images 02.jpg and 03.jpg):
Same as before with some additional subtitle information like threshold in pixels for each image.
Same as before with an added plot at the bottom displaying the result of a bootstrapped reconstruction using the two specified images.
Shows common tracks that are included in the final reconstruction (which is loaded from file). The second subplot shows reprojections for reconstructed 3D points and triangulation reprojections or triangulation failures for rejected tracks. The rejected tracks are triangulated using the final reconstruction cameras. 
The re-triangulation of the rejected tracks can only give an …
> Plot inlier improvements and reprojections

- bin/run_all
Something like this might help new users get up and running as the error otherwise reported isn't very intuitive.
> Error message on missing config.yaml

- opensfm/src/third_party/akaze/lib/AKAZE.cpp
std::sort comparison functions should return bool (or values convertible to bool) that satisfy strict weak ordering.
As written, these comparisons return -1, 0, or 1 which has undefined behavior resulting in seg faults.
> Fix AKAZE std::sort comparison functions

- opensfm/io.py
This is a single line change (ignoring whitespace) to improve robustness when importing bundler files.  It guards against the following KeyError...
```
Traceback (most recent call last):
File "/source/OpenSfM/bin/import_bundler", line 32, in <module>
io.import_bundler(args.dataset, args.bundleout, list_file, tracks_file, reconstruction_file)
File "/source/OpenSfM/opensfm/io.py", line 451, in import_bundler
camera = reconstruction.shots[shot_key].camera
KeyError: 'myfile.jpg'
```
> Guard track construction against missing shot_key

- viewer/reconstruction.html
This resolves issues of artifacts along the seams of equirectangular textures. 
Was working on a simple reconstruction viewer using reconstruction.html as a guideline and it took me a while working back from the mapillary-js source to figure out where the artifacts were coming from.
Relevant mapillary-js code:
https://github.com/mapillary/mapillary-js/blob/master/src/component/imageplane/ImagePlaneFactory.ts#L135
> Add minfilter to textures in viewer

- opensfm/exif.py
I'm using OpenSfM with images extracted from video at more than 1 fps.  Thus, it is desirable to have sub-second accuracy for the capture time when using `matching_time_neighbors`.
This PR checks the corresponding Exif SubSec tags and adds the value to the timestamp.
> Add sub-second time to Exif capture time.

- opensfm/commands/create_tracks.py
When checking which steps of `run_all` make use of multiple CPU cores, I noticed that `create_tracks` is the only command called by `run_all` that doesn't add to `profile.log`.  For my data set, it takes longer than the other fast commands, due to 24 million calls to `UnionFind.union`.
> Write profile data for create_tracks

- README.md
This was necessary to get OpenGV to install on OSX Sierra for me.
> Adds eigen dependency to Readme for OSX

- opensfm/matching.py
- opensfm/reconstruction.py
For a large reconstruction (50 seconds of video at 8 fps with neighbors +/- 15 seconds), it took about 15 minutes to set up the image pairs before the actual reconstruction started.  This PR reduces that time greatly by using multiprocessing on a system with 16 cores, 32 hyper threads (1 process: 859 seconds; 32 processes: 63 seconds).
Unfortunately, the time for calling `common_tracks` for all image pairs, not included in the above, is 50 seconds.  When attempting to include it in the multiprocessing, the time for pickling `graph` dominated and most workers were idle.  This was true even when grouping the tasks by `im1`.  It may be possible to get around this by passing the graph as an initializer for each worker but I didn't try that.
> Use multiprocessing when finding homography between image pairs

- opensfm/commands/match_features.py
- opensfm/config.py
Adds extra configuration option to match on consecutive images ordered by name.  Use case is when you have a sequence of images, e.g. ripped from a video, that are in linear order.  Substantially speeds up the matching step in these cases.
#82
> Image matching on consecutive images

- opensfm/data/sensor_data.json
Fix warning for image from DJI Phantom 4.
```
Could not find ccd_width in file. Use --force-ccd or edit the sensor_data.json file to manually input ccd width
Loaded DJI_0045.jpg | camera: dji fc330 | dimensions: 4000 x 3000 | focal: 3.61 | ccd: None
```
**Phantom 4**
Focal length: 3.64mm
CMOS size: 6.25 x 4.68mm (7.81 diagonal)
Sensor: 1/2.3” CMOS
Lens: FOV 94° 20 mm (35 mm format equivalent) f/2.8 focus at ∞
> Add sensor width for DJI Phantom 4.

- opensfm/commands/detect_features.py
- opensfm/dataset.py
- opensfm/features.py
Adding additional feature where you can mask out parts of the image on a frame by frame and pixel by pixel basis, rather than having to specify static rectangles for the whole range.
Masks should have the same name as the corresponding image, and are listed in the same way as images, i.e. you can provide a textfile listing them, or you can just dump them in a folder next to images, called 'masks'.  They should be image files of the same dimension as the original images.  The first channel is scanned, and if it is equal to 0 then features there are kept, and if it is non-zero they aren't. (i.e. for a black and white mask, any white areas of the mask are deemed not useful, e.g. watermarks, moving objects, and so on).
Is there any relevant documentation to update?  I've also not really …
> Allow per image masking

- opensfm/commands/mesh.py
- opensfm/dataset.py
- opensfm/io.py
reconstruction.meshed.py gets too large to be loaded in the browser viewer for large datasets, and minifying this mitigates this. See #126 
I wasn't sure exactly how much to minify.  Setting indent to 0 rather than 4 gets most of the space saving gain, and you can still open the files easily in text editors, they just look less nice.  Setting indent to None removes new lines as well, and then you can't open the files easily in text editors and it would be very hard to human read.
For Lund I got size of 7.7mb for indent=4, 2.2mb for indent=0, 1.9mb for indent=None.
Since it's nice to have output human readable unless there is a good reason not to, I gave json_dump an argument to minify, and only activate for this one file at the moment.  But happy to change to minify all files/some other …
> Minify reconstruction.meshed.py

- opensfm/src/CMakeLists.txt
- opensfm/src/third_party/vlfeat/vl/host.c
Two small fixes to allow OpenSFM to compile on non x86 architectures.
I'm trying to upstream all the fixes to allow OpenDroneMap run an ARM processors. For reference:
OpenDroneMap/OpenDroneMap/issues/484
> Compilation fixes for non x86 architectures

- bin/opensfm_run_all
- setup.py
`python setup.py install` now makes it so a version of run_all can be ran globally
> Making OpenSFM install more nicely

- opensfm/reconstruction.py
Seemed not to match the signature required - note in the normal bundle this conversion is applied.
> Match signature by converting id to string

- opensfm/io.py
Currently if you use io to load shots, the mesh doesn't get loaded even if it exists.
> When loading shots, load mesh if it exists

- opensfm/reconstruction.py
The fix for bundle_single_view appears to be in master but the fix for bundle_local is not - I think it must have just got lost in the merge.
> Convert shot.id to string as required by bundle adjuster

- opensfm/commands/match_features.py
Fixes an exception where using `matching_gps_neighbors: 0` or omitting matching_gps_neighbors in the config prevents feature matching from completing. Frames without GPS info will error out using the default config values.
This PR prevents the following exception:
```
Traceback (most recent call last):
File "/source/OpenSfM/bin/opensfm", line 34, in <module>
command.run(args)
File "/source/OpenSfM/opensfm/commands/match_features.py", line 26, in run
pairs = match_candidates_from_metadata(images, exifs, data)
File "/source/OpenSfM/opensfm/commands/match_features.py", line 166, in match_candidates_from_metadata
gps_neighbors, max_distance)
File "/source/OpenSfM/opensfm/commands/match_features.py", line 94, in match_candidates_by_distance
gps['latitude'], gps['longitude'], gps['altitude'], …
```
> fix(match_features): allow matching_gps_neighbors to be unset in config

- opensfm/config.py
The current comments don't reflect the behavior of:
https://github.com/mapillary/OpenSfM/blob/d96023b41606176d34a988443fca423444f27258/opensfm/commands/match_features.py#L111
```python
if max_neighbors <= 0:
  return set()
```
That is, 0 does not mean no limit; it means bail out of matcher. This PR remedies that.
> Fix config feature-matching comments

- bin/clean
Clean should return the data directory to the initial state.
Currently the features directory is is not cleaned. This patch
fixes that behaviour.
> Move features directory to trash on clean

- opensfm/exif.py
When a focal length is saved as exifread.utils.Ratio, it can't be got as float.
exifread sometimes save the exif info `'EXIF FocalLengthIn35mmFilm'` as exifread.utils.Ratio class, and it can't be converted to float. So I added the code to check the instance of the tag.
When `'EXIF FocalLengthIn35mmFilm'` is a decimal, it seems that the focal length is saved as  exifread.utils.Ratio class.
> fix(exif): Check the instance when getting exif tag as float

- bin/opensfm_run_all
Following #202 and http://blog.mapillary.com/update/2016/10/31/denser-3d-point-clouds-in-opensfm.html I found it valuable to always generate a point cloud at the end of the process.
> feature: add extra steps to yield a point cloud file

- opensfm/reconstruction.py
The fisheye camera parameters are not accounted for in the bundle adjustment.
> bug: account for fisheye camera type in reconstruction

- opensfm/align.py
For "align naive" option there is an error in the line 208. In the original code the for loop is: "for key, observations in groups.values()". But the iterable "groups.values()" doesn't have two elements per iteration, it only has one.
> Problem in the line 208.

- viewer/reconstruction.html
This pull request improves navigation for equirectangular images by determining valid movement directions using the current viewing direction, which is also kept constant when moving between images. This should fix #235.
It would probably be better if the first image viewed had the camera horizontal and kept the same heading as was used in orbit mode, but I didn't see a straightforward way to detect that the moving mode was just changed.
> Improve navigation for equirectangular images

- opensfm/config.py
- opensfm/matching.py
This needs reviewing as it changes the default behavior of robust_match_calibrated:
Before:
- ransac was run with a threshold of 0.004 (default value of
robust_matching_threshold)
- inliers were filtered with a threshold of 0.01 (fixed)
After:
- ransac and inliers use a threshold of 0.01 (default value of a new
parameter: robust_matching_calib_threshold)
It depends on #285 and branch 'vectorizations'
> Angular threshold

- opensfm/commands/extract_metadata.py
- opensfm/dataset.py
Avoid overwriting existing EXIF data when extracting metadata. After this change the EXIF files needs to be removed if one wants to re-extract EXIF.
> Check if EXIF exists when extracting metadata

- opensfm/exif.py
This fixes the exception caused when there is no exif/focal length data for the image.
> Fix exception caused by no EXIF focal length

- opensfm/io.py
A typo is causing GCP files with a UTM projection in the southern regions (ex. `WGS84 UTM 32S`) to fail with `zone_number = int(zone['-1']) TypeError: string indices must be integers, not str`.
First reported here: http://community.opendronemap.org/t/problem-using-a-gcp-file-in-the-southern-hemisphere-wgs84-utm-36s/495
> Fixed GCP UTM south region parser typo

- bin/plot_submodels_gps
- doc/source/large.rst
- opensfm/commands/create_submodels.py
- opensfm/config.py
- opensfm/dense.py
- opensfm/large/metadataset.py
- opensfm/large/tools.py
When creating submodels, links to the root masks and segmentation folders are created so that they can be used during the reconstruction of the submodels.
> Link segmentations and masks in submodel folders

- opensfm/config.py
- opensfm/dataset.py
- opensfm/large/metadataset.py
Allows masks to be used in metadatasets, and uses absolute paths as opposed to relative paths for specifying location of datasets.  
Previously running:
bin/opensfm create_submodels data/my_dataset
Would not copy across masks
Would have broken symlinks for all of the images.
Note:
How are you expected to use metadataset?  Is it a useable feature?  It doesn't seem to be documented anywhere.  If you create the metadataset without previously finding features and matches (or at least creating the folders) it creates broken symlinks and doesn't work when you try and run opensfm_run_all on the entire set.
However, if you do run detect_features and create_matches then when you run opensfm_run_all on the subsets it tries to rematch.  This would be fixed with #178.
I think it would be good if …
> Metadataset improvements

- viewer/reconstruction.html
This PRs makes the viewer display each reconstruction with a different pseudo-random color, for easier debugging purposes. We also display the reconstruction index below the thumbnail. Since Math.random() doesn't provide seed initialization, a pseudo-random-generator has been implemented, for reproducibility purposes.
> Show different reconstructions with different colors

- opensfm/commands/export_visualsfm.py
- opensfm/commands/undistort.py
- opensfm/dataset.py
Hello :hand:
This PR proposes a modification to the undistort command to optionally allow a user to export images in PNG format and optionally scale the images before saving them to disk.
It also modifies the export_visualsfm command to optionally allow a user to choose the extension that the NVM file should reference (to be used in combination with the undistort command) and optionally scale the focal length value (which is useful if we have resized the images to perform further processing / visualization with external programs).
Other export commands haven't been modified, but if I need to modify them as well to provide better consistency, just ask, I'd be happy to.
```
usage: opensfm undistort [-h] [--image_format {jpg,png}]
[--image_scale IMAGE_SCALE]
dataset
usage: opensfm …
```
> Added ability to undistort to PNG, scale images

- .gitmodules
- README.md
- doc/source/building.rst
- doc/source/reconstruction_module.rst
- licenses.csv
- opensfm/src/CMakeLists.txt
- opensfm/src/akaze.cc
- opensfm/src/csfm.cc
- opensfm/src/depthmap_wrapper.cc
- opensfm/src/hahog.cc
- opensfm/src/hahog.h
- opensfm/src/multiview.cc
- opensfm/src/openmvs_exporter.h
- opensfm/src/types.h
- setup.cfg
- setup.py
This PR replace the boost python based binding code with pybind11.
Main motivations:
- simpler to build for python 2 and 3
- simpler to maintain since pybind11 is included as a submodule. Support for different versions of boost python was difficult.
The only impact that this should have is that, in order to build opensfm, we now need first update git submodules with
```
git submodule update --init --recursive
```
To make sure we have `pybind11` code update.
> Use pybind11 instead of boost python

- opensfm/src/third_party/akaze/lib/AKAZEConfig.h
`OMP_MAX_THREADS` can now be specified without having to modify `AKAZEConfig.h`. This also serves as a safeguard against accidental check-in of a modified `AKAZEConfig.h`, which prevents messing up the default configuration.
> Enable overriding of default OpenMP number of threads limit in libAKAZE

- opensfm/commands/export_visualsfm.py
- opensfm/commands/undistort.py
- opensfm/config.py
- opensfm/dataset.py
This PR adds two config options for image undistortion
```
undistorted_image_format: jpg         # Format in which to save the undistorted images
undistorted_image_max_size: 100000    # Max width and height of the undistorted image
```
It is a continuation of #352 with the following differences:
- undistorting the different layers (image, mask, segmentation) is now done sequentially so that each can be configured easierly.
- the command line options are moved to config options so that they are accessible for all commands. Otherwise, one could undistort in png format while the `compute_depthmaps` command would keep trying to load jpg files.
> Add options to set undistorted image format and max size

- doc/source/building.rst
Changed: `git clone https://github.com/paulinus/opengv.git` to `git clone --recurse-submodules -j8 https://github.com/paulinus/opengv.git`
Notes:
opengv contains sub modules, we need recursive git cloning, otherwise not all the modules will be loaded.
> Update Installation Instructions

- opensfm/commands/export_openmvs.py
It looks like other uses of .keys() are just wrapped in list(), let me know if you would prefer that for this line also.
Test with:
```sh
bin/opensfm_run_all data/berlin
bin/opensfm export_openmvs data/berlin
```
Error:
```
Traceback (most recent call last):
File "bin/opensfm", line 34, in <module>
command.run(args)
File "/home/user/OpenSfM_python3/opensfm/commands/export_openmvs.py", line 26, in run
self.export(reconstructions[0], graph, data)
File "/home/user/OpenSfM_python3/opensfm/commands/export_openmvs.py", line 57, in export
exporter.add_point(coordinates, shots)
TypeError: add_point(): incompatible function arguments. The following argument types are supported:
1. (self: opensfm.csfm.OpenMVSExporter, arg0: numpy.ndarray[float64], arg1: list) -> None
```
> Resolve export_openmvs.py Python 3 compat issue.

- opensfm/commands/undistort.py
- opensfm/dataset.py
- opensfm/reconstruction.py
- opensfm/src/bundle.h
- opensfm/synthetic_data/synthetic_generator.py
- opensfm/test/data_generation.py
- opensfm/test/test_tracks.py
- opensfm/tracking.py
This PR makes 2D projection errors being scaled by their respective detected scale. Improves results on Strecha's bencmark by 25-50%.
A minor issue is that the feature were always exported by their actual pixel scale instead of a normalized one : hence a normalization hack.
Found a general issue in the bundle code, where errors should by scaled by `sqrt(1/std_deviation)` instead of just `1/std_deviation`
> feature: scale 2D projection errors by their detected scale

- opensfm/exif.py
@paulinus I am sorry for this. My SI units print with US customary units equivalents has a typo in the length of a mile in mm. So, I have double-checked twice now. The US customary units system defines an inch as exactly 25.4 mm, instead of 804667 / 31680 = 25.39984217… mm. I could not wrap around my head why the exact length of an inch in mm (in my SI units print) was not exactly a multiple of a mile in mm. Fortunately, the error is so marginal that it is negligible but it is better to be correct than sorry later.
> fix: typo in inch_in_mm

- opensfm/dataset.py
- opensfm/features.py
- opensfm/synthetic_data/synthetic_generator.py
- opensfm/tracking.py
This PR aims at correcting some hack introduced here (https://github.com/mapillary/OpenSfM/pull/417) : we want the feature scale to be properly set, at extraction time, when pixel position are normalized wrt. the image size.
To do so, we  :
- Moved features IO to the `features` module
- Added basic versioning. In the 0 version, normalized scale is set to the default config value (`0.004`)
- Removed the normalizing hack in `tracking`
- Added proper normalization in `features`
> feat:scale properly the feature scale

- opensfm/commands/undistort.py
Problem: when setting `undistorted_image_max_size` to a value lower than the images (eg. 100) the value of:
`factor = max_size / max(height, width)`
Always evaluates to 0 during undistortion.
Proposed solution: type cast to float the denominator.
> FIX: cast to float in undistort.py

- opensfm/commands/export_visualsfm.py
- requirements.txt
- setup.py
Currently calling `export_visualsfm` will read the entire dataset of images from disk to compute width and height for each image.
This can be sped up a lot by simply reading the header values instead of loading the entire image in memory.
Even on a small dataset (a few dozen images):
```
time opensfm/bin/opensfm export_visualsfm /datasets/test
real	0m9.027s
user	0m8.164s
sys	0m1.302s
```
Vs. the proposed change:
```
time opensfm/bin/opensfm export_visualsfm /datasets/test
real	0m0.802s
user	0m0.694s
sys	0m0.500s
```
I'm not sure if the function to compute the width/height should move moved elsewhere? Anyway, let me know if anything needs to be changed :pray: Thank you!
> Faster export to VisualSFM

- opensfm/exif.py
When Focal Plane Resolution Unit is present in exif,  function extract_sensor_width calls self.get_mm_per_unit(resolution_unit) with only one argument.  Added self as first argument. 
File "/home/test/OpenSfM/opensfm/exif.py", line 197, in extract_sensor_width
mm_per_unit = self.get_mm_per_unit(resolution_unit)
TypeError: get_mm_per_unit() takes exactly 1 argument (2 given)
> Add self parameter in  get_mm_per_unit function

- bin/colmap_export
- doc/source/dataset.rst
- opensfm/config.py
- opensfm/io.py
- opensfm/reconstruction.py
- opensfm/src/bundle/bundle_adjuster.h
- opensfm/src/bundle/src/bundle_adjuster.cc
- opensfm/src/bundle/src/projection_errors.h
- opensfm/src/csfm.cc
- opensfm/test/test_reconstruction_incremental.py
- opensfm/test/test_reconstruction_resect.py
- opensfm/test/test_tracks.py
- opensfm/test/test_triangulation.py
- opensfm/types.py
This PR robustify the incremental SfM pipeline by explicitely keeping track and storing inliers through the reconstruction process. This result in major improvement on traditional SfM datasets (ETH3D and Strecha). To do so, we had to :
- Use a second graph (called `inliers_graph`)through the incremental SfM, that keeps track of inliers.
- We now perform outliers filtering at the individual projection level instead of entire tracks.
- We introduce a triangulation variant based on robust/RANSAC triangulation. Not used by default as it didn't show any major improvment. See `triangulation_type` in `config`
- We also introduce a new scheme (`AUTO`) for filtering outliers based on the error distribution rather than a fixed threshold.  Can greatly improve results by is let deactivated for …
> feat: inliers graph

- opensfm/bow.py
- opensfm/commands/detect_features.py
- opensfm/commands/match_features.py
- opensfm/config.py
- opensfm/context.py
- opensfm/dataset.py
- opensfm/matching.py
- opensfm/pairs_selection.py
- opensfm/src/CMakeLists.txt
- opensfm/src/csfm.cc
- opensfm/src/matching.cc
- opensfm/src/matching.h
- opensfm/src/types.cc
- opensfm/src/types.h
- setup.py
This PR add bags-of-words (BoW) matching to OpenSfM. This branch is the combination of https://github.com/mapillary/OpenSfM/tree/feat-match-words, which adds BoW matching, and other commits that add pairs generation from BoW. More specifically, we did the following :
- Compute words assignemnts at feature extraction stage, when either matching or pairs generation is BoW-based.
- Add image-to-image BoW matching. 2x to 5x faster than FLANN-based matching with reduction in accuracy.
- Removed unused preemptive matching
- Moved pair generation code to a new module
- Added pairs generation using BoW distances, further controlled by `matching_bow_neighbors` in `config`
> feature: bag-of-words matching

- doc/source/_templates/layout.html
Some style overrides using brand colors. Doesn't touch `sphinx_rtd_theme`.
WIP.
> feat(docs): use brand colors in docs

- opensfm/reconstruction.py
If `len(reconstruction.points)` is `0` (which sometimes is the case), the program will fail with:
```
line 1279, in compute_statistics stats['average_track_length'] = float(stats['observations_count'])/len(reconstruction.points) ZeroDivisionError: float division by zero 
```
> Handle div by zero

- opensfm/commands/export_visualsfm.py
- opensfm/commands/extract_metadata.py
- opensfm/dataset.py
While `extract_metadata` seems I/O bound, I've noticed that processing with two processes yields almost 30% speed-up in performance.
With 78 images:
```
real	0m19.920s
user	0m16.316s
sys	0m3.808s
```
vs. proposed
```
real	0m14.724s
user	0m22.400s
sys	0m6.029s
```
Not sure if the added complexity is worth it, but thought I'd open a PR to see if there's interest.
> Faster extract_metadata when using use_exif_size: no

- doc/source/geometry.rst
- opensfm/commands/detect_features.py
- opensfm/commands/match_features.py
- opensfm/config.py
- opensfm/context.py
- opensfm/dataset.py
- opensfm/feature_loading.py
- opensfm/matching.py
- opensfm/pairs_selection.py
- opensfm/synthetic_data/synthetic_scene.py
- opensfm/test/conftest.py
- opensfm/test/test_bundle.py
- opensfm/test/test_matching.py
- opensfm/test/test_reconstruction_incremental.py
- opensfm/upright.py
This PR is the first in a series of 2, which aims at unifiying OpenSfM matching with Mapillary's production matching. This PR focuses on the pair matching part, and does the following :
- Move images matching main entry point, from `command` to `matching`
- Unify production and OpenSfM matching
- Add optional production-specific filters
- Add production feature cache
> Merge OpenSfM and production matching 2/2

- opensfm/commands/match_features.py
- opensfm/matching.py
- opensfm/pairs_selection.py
- opensfm/test/test_matching.py
- opensfm/test/test_reconstruction_incremental.py
This PRs adds a flag in the main matching routine for overwriting or not matching data when written.
Additionally, a couple of typos in pair selection have been fixed.
> feat: matching overwrite

- opensfm/commands/export_visualsfm.py
This PR adds support to export points along with camera positions in the NVM file format. This can be useful for examination of the output in programs such as VisualSFM or as an input to MVS programs that might need the sparse point cloud as an initialization step (for example https://github.com/alexlocher/hpmvs).
The default behavior of `export_visualsfm` is unchanged, but the `--points` flag now optionally allows to export points along with cameras.
Please let me know if changes are needed :pray:
> Export points option for VisualSFM exporter

- bin/plot_gcp.py
- opensfm/align.py
- opensfm/dataset.py
- opensfm/io.py
- opensfm/reconstruction.py
- opensfm/synthetic_data/synthetic_dataset.py
- opensfm/test/test_reconstruction_incremental.py
This PR aims at improving the alignment behaviour when using GPS and GCP.
More specifically, we propagate the use of `bundle_use_gps` and `bundle_use_gcp` in the alignment. Discussion is welcome whether we should have a distinct option or not.
The global behaviour is also changed as it is done before any bundle, hoping GPS/GCP error will be closer to optimum when starting the bundle. Additionally, we also support edge cases when we have only one or two GCP/GPS (scale/orientation ambiguity will remain though, no a-priori is being made).
Finally, we refactored code a bit so we can support correct topocentric frame when there is no GPS.
Yann
> feat: better gps and gcp align

- opensfm/feature_loading.py
- opensfm/matching.py
- opensfm/pairs_selection.py
This is a refactor on top of #462 to optionally mask the features inside the feature loader.
It complicates a bit the loader and simplifies the matching code that no longer needs to mask every loaded array.
We still cache the unmasked arrays.
For the flann index, we cache the masked and unmasked indices in different caches so that both can be loaded independently.
Also, to simplify, the flann index is always built and never loaded.
> Refactor load masked features

- opensfm/feature_loading.py
- opensfm/pairs_selection.py
There is something funky going on here, @YanNoun.
Before this fix, we are always rebuilding the index because we get `len(current_features)==3`
After the fix, running on lund we get a segmentation fault. The problem is that the flann index is created with a filtered array here
https://github.com/mapillary/OpenSfM/blob/master/opensfm/matching.py#L107-L108
This array is not cached and gets garbage collected. So the second time that we try to use the same index, it points to that array that no longer exists.
One way to solve that would be to filter the feature arrays before caching them.  It could be done in the feature loader itself.
> BROKEN  fix: get the number of features right

- opensfm/commands/detect_features.py
- opensfm/dataset.py
- opensfm/features.py
- opensfm/upright.py
We had a bug on the rotation matrix that rotates features according to the exif tag.
This PR fixes the bug and refactors the feature extraction code to always use the same mask.
> Fix mask for rotated images

- opensfm/test/data_generation.py
- opensfm/test/test_pairs_selection.py
This PR decreases the time it takes to run the unit test stage in CI by ~120 seconds. The unit test run time is still ~50 seconds longer than before the merge of https://github.com/mapillary/OpenSfM/pull/466 because of the feature extraction of the lund dataset which is required for the `match_candidates_from_metadata` tests.
With this PR the features are extracted once in a module fixture instead of once for each of the four tests.
> Decrease unit test time

- opensfm/config.py
- opensfm/matching.py
All matcher types now have the option to be run symmetrically or one-way.
> Add option for symmetric or one-way matching

- opensfm/align.py
- opensfm/exif.py
This PR aims at fixing two GPS issues :
- Defective GPS values, all values being the same. Which lead to further issue in computing alignment.
- DJI drones have buggy firmware versions (Mavic), where classic `GPSLatitude` tags had truncated values (leading to same-values issue, see above). Using DJI-specific XMP tags when available mitigates the issue.
Ping @pierotofy if you can test on more datasets. I got the issue on `hellasgarden' dataset taken with a Mavic Air (?), but can't remember where I got it from, thought it was from OpenSfM GH issues.
> fix: use DJI XMP EXIF and handle same-GPS case

- opensfm/large/tools.py
It seems that a regression was introduced in https://github.com/mapillary/OpenSfM/commit/4460775c5f371da107d452d9dffb9205bab1f6d2 as `add_absolute_position_constraint`'s signature does not allow a 6th parameter?
During testing the `add_camera_constraints_soft` seemed to work OK (results looked correct) by simply removing the key parameter. Not sure if `add_absolute_position_constraint` should be modified instead.
> Fix add_absolute_position_constraint call

- opensfm/exif.py
- opensfm/io.py
- opensfm/mesh.py
- opensfm/reconstruction.py
- opensfm/src/bundle/bundle_adjuster.h
- opensfm/src/bundle/src/bundle_adjuster.cc
- opensfm/src/bundle/src/projection_errors.h
- opensfm/src/csfm.cc
- opensfm/test/test_types.py
- opensfm/types.py
This PR introduce a new camera model dubbed `dual` than can seamlessly switch between fisheye and perspective projection using an additional parameter called `transition`. More formally, one can rewrite the projection as : 
`proj(dual) = transition * proj(perspective) + (1 - transition) * proj(fisheye)`
Inverse projection (aka. `bearings`) is done using an inverse iterative scheme (only 3 iterations are sufficient), as one can't retrieve the incident angle `theta` from the the distorted points.
`transition` is soft-constrained between 0 and 1 in the bundle, using a log-barrier penalty.
Corresponding `mapillary_sfm` commit is here : https://github.com/mapillary/mapillary_sfm/commit/3330e863714877e8c6674a4e28adbd34b68b3607
> feat: added dual camera model

- bin/export_bundler
- bin/export_pmvs
- bin/migrate_undistort.sh
- bin/plot_depthmaps
- doc/source/dataset.rst
- opensfm/commands/compute_depthmaps.py
- opensfm/commands/export_geocoords.py
- opensfm/commands/export_openmvs.py
- opensfm/commands/export_ply.py
- opensfm/commands/export_visualsfm.py
- opensfm/commands/undistort.py
- opensfm/dataset.py
- opensfm/dense.py
- setup.cfg
This PR moves all files related to undistorted reconstructions to the `undistorted` subfolder. This includes undistorted images, masks, reconstructions, and depth maps. This makes it easier to have different undistorted versions of a reconstruction or to store them in other subfolders while decluttering the main folder.
The dataset methods related to undistorted data are moved to a new `UndistortedDataSet` class which keeps track of which subfolder the undistorted data is in.
This PR breaks the folder structure compatibility because depthmaps are stored in a different place. We should release a version before merging this so we can refer to it as the most recent using the older folder structure.
The new folder structure looks like tihs:
```
project/
├── config.yaml
├── images/
├── masks/ …
```
> Refactor undistorted folder

- doc/source/using.rst
Python3 has a slightly different command for launching an HTTP server. This pull request adds that command to `using.rst`.
> Add Python3 http.server command.

- bin/plot_inliers
- opensfm/config.py
- opensfm/matching.py
- opensfm/multiview.py
- opensfm/reconstruction.py
This PR aims at speeding-up the matching by reducing the number or iterations during nonlinear refinement of the relative pose, leveraging a patch to opengv that allow such.
We do 10 iterations during matching, and 1K (default) during two view reconstruction. Experiments shows a nice speed-up (1.6x factor) and no regression in matching results.
> feat: use opengv iteration control

- opensfm/exif.py
Hello :hand:
This is a simple fix for a problem I encountered while processing a dataset.
If the camera model is `brown` and the code ends up calling `default_calibration`, the resulting dictionary does not include the necessary keys to initialize the brown model (which ends up triggering an exception when accessing `focal_x`).
Specifically, if this line is called https://github.com/mapillary/OpenSfM/blob/1eab045b4565d4f3ab8669d23908daa693761341/opensfm/exif.py#L448 followed by https://github.com/mapillary/OpenSfM/blob/1eab045b4565d4f3ab8669d23908daa693761341/opensfm/exif.py#L454 the program crashes.
Returning the proper dict keys fixes the problem.
> [Bug] Return default calib values for brown camera

- opensfm/reconstruction.py
I've found that certain cameras report a GPS DOP value of 0. I interpret this as meaning "no data" instead of indicating absolute precision (that doesn't seem possible).
I can post examples of problems with reconstructions when GPS DOP is set to zero if needed.
Let me know your thoughts?
> Set GPS DOP value to 15 (default) if EXIF reports it as 0

- opensfm/commands/export_visualsfm.py
Hello :hand:
This PR proposes the addition of a `--image_list` option to the `export_visualsfm` program. This can be useful for cases where a subset of the reconstruction needs to be exported (for example, to extract the reconstruction for a particular camera in datasets that may use multiple cameras).
The default behavior of the program is unchanged.
It also changes the brown model approximation to include both `focal_x` and `focal_y` (to be consistent with https://github.com/mapillary/OpenSfM/blob/master/opensfm/commands/undistort.py#L249)
Please let me know if this could be of use to the project and if changes are needed. :pray:
> Add --image_list option to export_visualsfm

- opensfm/exif.py
Hello! :hand:
It looks like `get_mm_per_unit` was missing a few enum values for units. This causes errors with certain camera vendors (found this from a Parrot Sequoia dataset). The enum values are taken (per  comment indications) directly from https://www.sno.phy.queensu.ca/~phil/exiftool/TagNames/EXIF.html (`FocalPlaneResolutionUnit`).
I've introduced the `cm_in_mm` and `um_in_mm` variables to be consistent with the `inch_in_mm` conversion. 
:clinking_glasses:
> Add support for more FocalPlaneResolutionUnit values

- opensfm/commands/undistort.py
- opensfm/dataset.py
Hello :hand:
This PR proposes the addition of the `IMREAD_UNCHANGED` flag to the undistort command.
Reason:
When loading images with a single band or N-band (!= 3) camera, OpenCV will convert the image to a 3 channel image (losing the original band information).
Discussion for breaking changes and additional features:
This may break certain applications *if* such applications take as input single band or N-band images (N != 3) and make assumptions that the output of undistortion is always a 3 band RGB image. If that's the case, perhaps it might be beneficial to add a `--unchanged` or `--preserve-bands` flag to the undistort command. If that's the case, please let me know and I'll add it. :pray:
> use IMREAD_UNCHANGED for undistort

- opensfm/data/sensor_data.json
- opensfm/exif.py
Xiaomi gimbal camera data is missing.
Fix extra space in the beginning of model string due to non valid utf8 bytes in exif data.
> add xiaomi gimbal camera ccd width, fix extra space

- bin/focal_from_exif
- opensfm/commands/extract_metadata.py
- opensfm/exif.py
`DateTime*` time stamps are adjusted by time zone offsets `OffsetTimeOriginal`, `OffsetTimeDigitized`, and `OffsetTime` respectively, if available. Otherwise, UTC is naively assumed on any `DateTime*`.
The time stamp is extracted in the following order of decreasing precedence:
* `GPSDateStamp` and `GPSTimeStamp`
* `DateTimeOriginal` + `SubSecTimeOriginal` + `OffsetTimeOriginal`
* `DateTimeDigitized` + `SubSecTimeDigitized` + `OffsetTimeDigitized`
* `DateTime` + `SubSecTime` + `OffsetTime`
* `DateTimeOriginal` + `SubSecTimeOriginal` (*UTC*)
* `DateTimeDigitized` + `SubSecTimeDigitized` (*UTC*)
* `DateTime` + `SubSecTime` (*UTC*)
> Add time zone support to time stamp extraction

- opensfm/matching.py
- opensfm/multiview.py
- opensfm/reconstruction.py
- opensfm/src/geometry/pose.h
- opensfm/src/geometry/python/pybind.cc
- opensfm/src/geometry/src/pose.cc
- opensfm/src/geometry/src/triangulation.cc
- opensfm/src/geometry/triangulation.h
- opensfm/src/robust/relative_pose_model.h
- opensfm/test/test_multiview.py
- opensfm/test/test_triangulation.py
This PR move a step forward in removing `opengv` by implementing in-house relative pose refinement and two-view triangulation. We also refactored triangulation methods and add some additional unit tests.
> feat: in-house relative pose refinement

- opensfm/multiview.py
- opensfm/src/geometry/absolute_pose.h
- opensfm/src/geometry/python/pybind.cc
- opensfm/src/geometry/relative_pose.h
- opensfm/src/geometry/src/relative_pose.cc
- opensfm/src/geometry/transform.h
- opensfm/src/robust/absolute_pose_known_rotation_model.h
- opensfm/src/robust/absolute_pose_model.h
- opensfm/src/robust/instanciations.h
- opensfm/src/robust/model.h
- opensfm/src/robust/python/pybind.cc
- opensfm/src/robust/relative_pose_model.h
- opensfm/src/robust/relative_rotation_model.h
- opensfm/src/robust/robust_estimator.h
- opensfm/src/robust/src/instanciations.cc
- opensfm/test/test_multiview.py
- opensfm/test/test_robust.py
This PR adds the relative rotation robust estimator.
As a bonus, we also greatly improve the speed of most estimator by allowing the `model` to precompute a part of the cost function by using the `ThresholdAdapter` function (identity by default). Typically, we use it for adapting the threshold `t` to be replaced with `1-cos(t)` so the actual angle cost `acos(dot(...))` become `1 - dot(...)` leading to 10x speed-up.
> feat: relative rotation

- opensfm/large/tools.py
The original use of groupby expects a sorted transformations.keys() iterable. When this is not true, the function will repeatedly reload the original dataset and discard random alignments.
This results in alignment failures between submodels of large reconstructions.
> Failure on unsorted data in apply_transformations

- opensfm/exif.py
Hello :hand:
I've found a camera (DJI Zenmuse Z30) that reports "bad" `FocalPlaneXResolution` values of `0`, triggering a division by zero error.
Since `extract_sensor_width` can return `None` I think it should return that instead of failing.
Related: https://github.com/OpenDroneMap/ODM/issues/1089
> Catch division by zero

- bin/run_synthetic_test
- opensfm/src/geometry/relative_pose.h
- opensfm/synthetic_data/synthetic_examples.py
- opensfm/synthetic_data/synthetic_scene.py
- opensfm/test/conftest.py
- opensfm/test/data_generation.py
- opensfm/test/test_matching.py
- opensfm/test/test_multiview.py
- opensfm/test/test_reconstruction_resect.py
- opensfm/test/test_robust.py
- opensfm/test/test_tracks.py
This PR aims at improving the test coverage of geometry and robust modules. More specifically, we aims at testing on a variety of poses and pairs and not a single one. To do so, we had to :
- Refactor the cube dataset generator under the `SyntheticScene` umbrella.
- The above dataset now samples random camera on a sphere around a cube of point.
- Pair and pose fixture now uses the above for generating N poses and pairs
- All robust and geometry unit tests now uses the above fixture, thus running N tests.
- We slightly tweaked some test : removed iteration reduction for some, increased some `{r,a}tol`, allowed minimal geometry estimators to fail in case of colinear/coplanar points.
- As a bonus, we found and fixed a bug (missing normalization)
> feat: test with more poses and pairs

- opensfm/src/robust/CMakeLists.txt
- opensfm/src/robust/essential_model.h
- opensfm/src/robust/src/absolute_pose_known_rotation_model.cc
- opensfm/src/robust/src/absolute_pose_model.cc
- opensfm/src/robust/src/line_model.cc
- opensfm/src/robust/src/relative_pose_model.cc
- opensfm/src/robust/src/relative_rotation_model.cc
The static const int members are optimized out when building
in release mode. Therefore, it has been working well having
them declared in the header only. However, when building in
debug mode, the missing definition yields to undeclared
symbols in the library.
> fix: define static members

- bin/import_colmap
Script to convert a COLMAP reconstruction into the OpenSfM format.
It can import the COLMAP sqlite database:
- Cameras
- Features (w. scale)
- Descriptors
- Matches
As well as the COLMAP reconstruction from `cameras.txt`, `points3D.txt` and `images.txt` into:
- Tracks
- Final optimized cameras
- Shots
- 3D points
> feat: script to import from colmap

- opensfm/src/dense/CMakeLists.txt
This PR fixes a linker error during building:
```[ 70%] Linking CXX executable dense_test
CMakeFiles/dense_test.dir/test/depthmap_test.cc.o: In function `cvflann::anyimpl::big_any_policy<cv::String>::static_delete(void**)':
depthmap_test.cc:(.text._ZN7cvflann7anyimpl14big_any_policyIN2cv6StringEE13static_deleteEPPv[_ZN7cvflann7anyimpl14big_any_policyIN2cv6StringEE13static_deleteEPPv]+0x15): undefined reference to `cv::String::deallocate()'
CMakeFiles/dense_test.dir/test/depthmap_test.cc.o: In function `cvflann::anyimpl::big_any_policy<cv::String>::move(void* const*, void**)':
depthmap_test.cc:(.text._ZN7cvflann7anyimpl14big_any_policyIN2cv6StringEE4moveEPKPvPS5_[_ZN7cvflann7anyimpl14big_any_policyIN2cv6StringEE4moveEPKPvPS5_]+0x10): undefined reference to `cv::String::deallocate()' …
```
> build: fix linker error with opencv

- opensfm/src/geometry/absolute_pose.h
- opensfm/src/geometry/relative_pose.h
- opensfm/src/geometry/src/triangulation.cc
- opensfm/src/geometry/transform.h
This PR replaces `auto` by the actual `Eigen` types to avoid double computations or potential incorrect results as suggested in [Eigen Pitfalls](https://eigen.tuxfamily.org/dox/TopicPitfalls.html).
> fix: replace auto by Eigen types 

- opensfm/src/bundle/src/bundle_adjuster.cc
- opensfm/src/geometry/camera.h
- opensfm/src/geometry/camera_functions.h
- opensfm/src/geometry/src/camera.cc
- opensfm/src/geometry/test/camera_test.cc
This PR aims at adding analytical computation of camera projection functions, with the hope, it will speed-up bundle adjustment process. To do so, we had :
- Generalize camera functions as `CameraFunctors`
- Implement local jacobians of such camera functors.
- Implement helper that automatically chain the above local jacobian, along the function composition.
- Re-use the same to re-express the generic camera models.
- Add corresponding unit test that uses `Eigen` `autodiff` to check for correctness.
As a bonus, we changed the parameter indexing in the camera class so it matches the ordering of the camera functions composition. This is still cumbersome and needs to be changed.
> feat: analytical jacobian of cameras

- annotation_gui_gcp/imageSugestion.py
- opensfm/align.py
- opensfm/io.py
- opensfm/large/tools.py
- opensfm/reconstruction.py
- opensfm/src/map/python/pybind.cc
- opensfm/src/map/shot.h
- opensfm/src/map/src/shot.cc
- opensfm/synthetic_data/synthetic_metrics.py
- opensfm/test/test_types.py
- opensfm/types.py
The `types.ShotMetadata` class used `None` as a sentinel value for missing metadata. Doing so in c++/pybind gets complicated. Instead, we explicitly add a `has_value` property to each member.
Also, we take the opportunity to rename some old, wrong names such as `gps_dop` which is actually storing the GPS accuracy in meters and not the GPS DOP.
There are some ugly parts to handle both `types.Shot` and `pymap.Shot` objects. Those should go away when removing `types.Shot`
> Make shot measurements optional without using None

- opensfm/data/sensor_data.json
Adds missing entries for Phantom4 Pro drone cameras.
> Add Phantom4 Pro camera sensor width

- opensfm/config.py
- opensfm/features.py
Hey ✋ all,
I've exposed the flann index algorithm choice (KDTREE and KMEANS) in the config file. This has several possible uses:
- Choosing KDTREE can make it faster to build the index, which on some datasets seem to decrease overall runtime.
- KMEANS in certain postprocessed datasets can crash; this is really rare, but I've found at least one dataset that has certain trouble images (images that have a large section where no features can be found, eg. any image with a large black patch, either due to corruption, thresholding or for masking reasons).
This PR leaves the default as KMEANS, so the default logic of the program is unchanged.
Hope this can be useful to others.
(Paper with runtime/accuracy comparisons of the two algorithms: …
> Expose flann index algorithm

- opensfm/config.py
- opensfm/reconstruction.py
- opensfm/src/bundle/CMakeLists.txt
- opensfm/src/bundle/bundle_adjuster.h
- opensfm/src/bundle/python/pybind.cc
- opensfm/src/bundle/src/bundle_adjuster.cc
- opensfm/src/bundle/src/projection_errors.h
- opensfm/src/bundle/test/reprojection_errors_test.cc
- opensfm/src/foundation/numeric.h
- opensfm/src/foundation/src/numeric.cc
- opensfm/src/geometry/camera_functions.h
- opensfm/src/geometry/test/camera_test.cc
This PR aims at effectively plugging the analytic derivatives in the bundle adjustment code (see https://github.com/mapillary/OpenSfM/pull/610). To do so we had to :
- Add a functor that compute worl-to-camera transformation along with its derivatives. Such derivatives are themselves implemented using `angle axis` (along with `Jet`) to `3x3` (analytic) and then chained.
- Compose the above functor with the projection ones to get the full projection function.
- Use the above in some cost function (both 2D and 3D-bearing)
- Activate the instantiation of the above through some boolean, so it is de-activated for now and we can test it.
- Added the corresponding unit test of all of the above to ensure no-regression wrt. to the auto-differentiated derivatives.
> feat: plug analytical derivatives in bundle

- opensfm/reconstruction.py
- opensfm/src/geometry/src/triangulation.cc
- opensfm/src/geometry/triangulation.h
- opensfm/test/test_triangulation.py
This PR fixes runtime crash behaviour on when using Clang. By replacing `py::object` return types with proper `Eigen` + `STL` ones, we unify both return types in `geometry` as well as fixing the crashes.
> fix: pybing+CLANG

- opensfm/feature_loading.py
- opensfm/large/tools.py
- opensfm/matching.py
- opensfm/pairs_selection.py
- opensfm/test/test_matching.py
- opensfm/vlad.py
- requirements.txt
- setup.py
Now that we are python 3 only, we can use python's owns lru cache instead of repoze.lru.
Python's lru cache comes only as a decorator. So a bit of refactoring was needed to make use of it.
We lose the ability to cache points and colors independently when we load points, features and color.
We now cache the masked features also, since those are the ones we load most of the time. So we avoid having to mask the features each time we get them from cache.
> refactor: use python 3 lru_cache instead of repoze.lru
