bin/plot_features
bin/plot_matches
bin/plot_tracks

* Adding titles with image names and number of features/matches to plots. 
* Showing all figures for plot_tracks. 
* Fixing typo for feature load in plot_features.

Titles in plots and showing all figures.

---

viewer/js/OrbitControls.js
viewer/js/journey.js
viewer/reconstruction.html

I have made an attempt at enhancing the journey experience by implementing a journey class that moves with constant speed.
A number of changes have been made to journey.js. The following classes have been added or changed. 
* LinearCurve - Inheriting from Three.Curve and is used to retrieve the position in the path at specific points in time.
* JourneyBase - Base class with functions used by inheriting classes such as calculating the shortest path. Defines the empty virtual methods start and stop which should be overridden by classes extending JourneyBase.
* Journey - Extends JourneyBase, otherwise the same functionality as before.
* SmoothJourney - Extends JourneyBase. Continously calculates the current position and viewing direction based on a linear curve created from the nodes in the …

Constant speed journey

---

bin/navigation_graph
config.yaml
data/berlin/config.yaml
viewer/js/journey.js
viewer/reconstruction.html

I have made the following journey changes to improve the movement:
* Preferred edge distance for navigation graph. Changing image planes too fast makes the movement a little bit hacky. Therefore a config value for preferred distance has been added. Default is set to six meters/units.
* Handling vertical changes in viewing direction and motion that are too large.
* Handling general rotation to avoid to much rotation around camera Z-axis (e.g. images turned upside down).
* Weighting distance, general rotation and motion when calculating the best edges to promote straight movement.
* Config values for navigation thresholds.
* To avoid unstable behaviour at the destination node because of skipped nodes the preferred distance graph is merged with the original shortest distance graph on the …

Journey improvements

---

README.md

Change OpenGV instructions once the python bindings PR is merged into main repo.

Add python opengv branch instructions to readme

---

README.md

I made a small correction to the opengv docs so that they can simply be copy pasted into the shell.

Fixing up opengv doc

---

opensfm/dataset.py
opensfm/io.py

Streaming JSON to file reduces memory overhead

Stream JSON to file

---

opensfm/data/sensor_data.json
opensfm/data/sensor_data_detailed.json

Signed-off-by: Patrick José Pereira <patrickelectric@gmail.com>

Add Canon PowerShot G9 X

---

opensfm/data/sensor_data.json

Added the camera of the DJI Mavic based on VFX Data:
http://vfxcamdb.com/dji-mavic/

Added DJI FC220 Camera (DJI Mavic)

---

opensfm/multiview.py

Thank you for providing great tools!

[Fix] singular typo in multiview.py

---

README.md

Update Mac OSX dependencies installation instruction as in #211 Thank you!

[Doc] Update mac osx dependency installation

---

opensfm/commands/export_ply.py
opensfm/dataset.py
opensfm/io.py

This will enable producing a sparse point cloud without the camera positions.

add optional --no-camera when saving reconstruction ply

---

opensfm/dataset.py
opensfm/features.py

fix: use flann_Index both in opencv2 and opencv3

---

opensfm/commands/export_geocoords.py

#254 This will create a transformation.txt file in the data base directory. It can then be parsed by other means.

Write geocoords transformation to file via #254

---

opensfm/types.py

I'm not sure if the naming conventions are the best.

vectorized version of back_project

---

opensfm/commands/create_submodels.py
opensfm/large/metadataset.py

There may be a better way to implement this, but I want to have the clusters (w/o neighbors) saved as geojson so we can create cutlines for merging the ODM orthos together. 
If you suggest changes I will happily implement them.

Save clusters as geojson

---

bin/plot_features
bin/plot_inliers
bin/plot_matches
opensfm/commands/match_features.py
opensfm/io.py

These scripts now run on python3, plus removal of unneeded argument in match_candidates_by_order function.

Fix+small clean up of plot scripts

---

opensfm/exif.py

Most dedicated cameras report the focal length and sensor size in the EXIF header. Traditionally, only few smartphones have been reporting this data but with the latest smartphones on the market, more and more devices report this crucial data too. This data should finally enable correct camera calibration and ultimately also improve reconstruction quality (mainly precision with increasing distance).
For this feature to work the EXIF header must have the `FocalLength`, `FocalPlaneXResolution`, and `FocalPlaneResolutionUnit` tags. Meta data extraction still falls back to database values on known cameras which do not report the required EXIF tags or to the default focal ratio (`default_focal_prior`) if the camera could not be found in the database. Please note that many of the sensor size …

feature: Extract true sensor width and focal length from EXIF

---

opensfm/align.py
opensfm/reconstruction.py

This PR fixes some one-liners potential issues, but these might have great consequences (hence the requested review).

One-liners that might have consequences

---

opensfm/reconstruction.py

When running local bundle, we remember which points were optimized and remove outliers only from those points.
These speeds up large reconstructions where there might be a lot of reconstructed points that are not being optimized by the local bundle

feat: remove outliers only from points that moved

---

bin/plot_inliers
opensfm/commands/detect_features.py
opensfm/config.py
opensfm/dataset.py
opensfm/matching.py

They are now computed on the fly when needed, so no need to compute and store during detect_features

Stop precomputing flann indices

---

doc/source/using.rst

fix: fixed path to dense point cloud reconstruction

---

opensfm/align.py

Noticed while reviewing a log from Open Drone Map.

Fix a small spelling error in a log message.

---

doc/source/building.rst
licenses.csv
opensfm/matching.py
opensfm/multiview.py
opensfm/reconstruction.py
opensfm/src/geometry/transform.h
opensfm/src/robust/absolute_pose_model.h
opensfm/src/robust/instanciations.h
opensfm/src/robust/random_sampler.h
opensfm/src/robust/relative_pose_model.h
opensfm/src/robust/relative_rotation_model.h
opensfm/src/robust/robust_estimator.h
opensfm/src/robust/src/instanciations.cc
opensfm/test/test_matching.py
opensfm/test/test_multiview.py

This PRs aims at removing completely `opengv` leaving us with our own `geometry` and `robust` estimators.

refactor: remove dependency on opengv

---

opensfm/geotag_from_gpx.py
requirements.txt

fix: remove loky (joblib has its own), and gpxpy (only one script)

---

opensfm/commands/commands.py
opensfm/exif.py
opensfm/src/bundle/bundle_adjuster.h
opensfm/src/bundle/src/motion_prior_terms.h
opensfm/src/bundle/src/projection_errors.h
opensfm/src/dense/depthmap_bind.h
opensfm/src/features/hahog.h
opensfm/src/features/src/hahog.cc
opensfm/src/features/src/matching.cc
opensfm/src/foundation/python_types.h
opensfm/src/foundation/src/types.cc
opensfm/src/geometry/python/pybind.cc
opensfm/src/geometry/triangulation.h
opensfm/src/map/landmark.h
opensfm/src/map/pybind_utils.h
opensfm/src/map/shot.h
opensfm/src/map/src/shot.cc
opensfm/test/data_generation.py

The goal is to get the internal and external repos in sync so that the automated syncs can start.  It is ok to let non-critical errors in. We should fix them right after.

chore: sync with fb internal changes

---

bin/opensfm.py

The internal and external repositories are out of sync. This attempts to brings them back in sync by patching the GitHub repository. Please carefully review this patch. You must disable ShipIt for your project in order to merge this pull request. DO NOT IMPORT this pull request. Instead, merge it directly on GitHub using the MERGE BUTTON. Re-enable ShipIt after merging.

Re-sync with internal repository
